package server

import (
	"net/http"
)

func registerGradingRoutes(mux *http.ServeMux, ctx routerContext) {
	mux.Handle("PUT /api/v1/answer-segments/{id}/answer", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.RecordAnswer))
	mux.Handle("POST /api/v1/answer-segments/{id}/rule-grade", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.RuleGrade))
	mux.Handle("GET /api/v1/answer-segments/{id}/ai-grades", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.ListGrades))
	mux.Handle("POST /api/v1/questions/{id}/scoring-rules", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.CreateScoringRule))
	mux.Handle("GET /api/v1/questions/{id}/scoring-rules", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.ListScoringRules))
	mux.Handle("PATCH /api/v1/scoring-rules/{id}", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.UpdateScoringRule))
	mux.Handle("POST /api/v1/scoring-rules/{id}/publish", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.PublishScoringRule))
	mux.Handle("GET /api/v1/answer-sheet-templates/{id}/omr-calibrations", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.ListOMRCalibrations))
	mux.Handle("POST /api/v1/answer-sheet-templates/{id}/omr-calibrations", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.CreateOMRCalibration))
	mux.Handle("GET /api/v1/omr-calibrations/{id}", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.GetOMRCalibration))
	mux.Handle("POST /api/v1/omr-calibrations/{id}/cases/{caseId}/label", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.LabelOMRCalibrationCase))
	mux.Handle("POST /api/v1/omr-calibrations/{id}/approve", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.ApproveOMRCalibration))
	mux.Handle("POST /api/v1/omr-calibrations/{id}/revoke", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.RevokeOMRCalibration))
	mux.Handle("POST /api/v1/omr-calibrations/{id}/discard", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.DiscardOMRCalibration))
	mux.Handle("GET /api/v1/exams/{examId}/scoring-readiness", ctx.guards.requireGradingManage(ctx.guards.withScopedExam(ctx.modules.Grading.GradingHandler.GetScoringReadiness)))
	mux.Handle("POST /api/v1/exams/{examId}/scoring-runs", ctx.guards.requireGradingManage(ctx.guards.withScopedExam(ctx.modules.Grading.GradingHandler.StartScoringRun)))
	mux.Handle("GET /api/v1/exams/{examId}/scoring-runs/commands/{commandId}", ctx.guards.requireGradingManage(ctx.guards.withScopedExam(ctx.modules.Grading.GradingHandler.RecoverScoringCommand)))
	mux.Handle("GET /api/v1/exams/{examId}/scoring-summary", ctx.guards.requireGradingManage(ctx.guards.withScopedExam(ctx.modules.Grading.GradingHandler.GetScoringSummary)))
	mux.Handle("GET /api/v1/exams/{examId}/automation-results", ctx.guards.requireGradingManage(ctx.guards.withScopedExam(ctx.modules.Grading.GradingHandler.GetExamAutomationResults)))
	mux.Handle("GET /api/v1/scoring-runs/{runId}", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.GetScoringRun))
	mux.Handle("GET /api/v1/scoring-runs/{runId}/ai-batches", ctx.guards.requireGradingManage(ctx.modules.Grading.SubjectiveHandler.ListScoringRunBatches))
	mux.Handle("POST /api/v1/scoring-runs/{runId}/cancel", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.CancelScoringRun))
	mux.Handle("POST /api/v1/scoring-runs/{runId}/retry-failed", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.RetryFailedScoringRun))
	mux.Handle("POST /api/v1/answer-segments/{id}/reprocess-score", ctx.guards.requireGradingManage(ctx.modules.Grading.GradingHandler.ReprocessSegmentScore))
	mux.Handle("POST /api/v1/answer-segments/{id}/subjective-ai-grade", ctx.guards.requireGradingManage(ctx.modules.Grading.SubjectiveHandler.Grade))
	mux.Handle("POST /api/v1/subjective-grading-batches", ctx.guards.requireGradingManage(ctx.modules.Grading.SubjectiveHandler.CreateBatch))
	mux.Handle("GET /api/v1/subjective-grading-batch-commands/{commandId}", ctx.guards.requireGradingManage(ctx.modules.Grading.SubjectiveHandler.RecoverBatchCommand))
	mux.Handle("GET /api/v1/subjective-grading-batches/{batchId}", ctx.guards.requireGradingManage(ctx.modules.Grading.SubjectiveHandler.GetBatch))
	mux.Handle("GET /api/v1/subjective-grading-batches/{batchId}/failed-segments", ctx.guards.requireGradingManage(ctx.modules.Grading.SubjectiveHandler.GetFailedBatchSegments))
	mux.Handle("GET /api/v1/subjective-grading-batches/{batchId}/enqueue-command", ctx.guards.requireGradingManage(ctx.modules.Grading.SubjectiveHandler.RecoverEnqueueCommand))
	mux.Handle("POST /api/v1/subjective-grading-batches/{batchId}/enqueue", ctx.guards.requireGradingManage(ctx.modules.Grading.SubjectiveHandler.EnqueueBatch))
	mux.Handle("POST /api/v1/ai-grades/{id}/verify-evidence", ctx.guards.requireEvidenceManage(ctx.modules.Grading.EvidenceHandler.Verify))
	mux.Handle("PUT /api/v1/exams/{examId}/double-mark-policy", ctx.guards.requireReviewManage(ctx.guards.withScopedExam(ctx.modules.Grading.ReviewHandler.SetExamDoubleMarkPolicy)))
	mux.Handle("PUT /api/v1/questions/{id}/double-mark-policy", ctx.guards.requireReviewManage(ctx.modules.Grading.ReviewHandler.SetQuestionDoubleMarkPolicy))
	mux.Handle("GET /api/v1/double-mark-policies", ctx.guards.requireReviewManage(ctx.modules.Grading.ReviewHandler.ListDoubleMarkPolicies))
	mux.Handle("POST /api/v1/double-mark-sessions", ctx.guards.requireReviewManage(ctx.modules.Grading.ReviewHandler.CreateDoubleMarkSession))
	mux.Handle("GET /api/v1/double-mark-sessions", ctx.guards.requireReviewManage(ctx.modules.Grading.ReviewHandler.ListDoubleMarkSessions))
	mux.Handle("GET /api/v1/double-mark-sessions/{id}", ctx.guards.requireReviewManage(ctx.modules.Grading.ReviewHandler.GetDoubleMarkSession))
	mux.Handle("POST /api/v1/arbitration-tasks", ctx.guards.requireArbitrationManage(ctx.modules.Grading.ReviewHandler.CreateArbitrationTask))
	mux.Handle("GET /api/v1/arbitration-tasks", ctx.guards.requireArbitrationWork(ctx.modules.Grading.ReviewHandler.ListArbitrationTasks))
	mux.Handle("GET /api/v1/arbitration-tasks/{id}", ctx.guards.requireArbitrationWork(ctx.modules.Grading.ReviewHandler.GetArbitrationTask))
	mux.Handle("POST /api/v1/arbitration-tasks/{id}/assign", ctx.guards.requireArbitrationManage(ctx.modules.Grading.ReviewHandler.AssignArbitrationTask))
	mux.Handle("POST /api/v1/arbitration-tasks/{id}/submit", ctx.guards.requireArbitrationWork(ctx.modules.Grading.ReviewHandler.SubmitArbitration))
}
